print("Enter the number 1")
num1=input()
print("Enter the number 2")
num2=input()
x= int(98.6)
try:
    print("The sum of these two number is",int(num1)+int(num2))
except Exception as e:
    print(e)

print("This is me")
"""try and exception is used to print the statment after the errored statment here e is just and example we
can use any"""
